version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: emrahkk/kube-echo      
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    environment:
      TAG: << pipeline.git.tag >>
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:$CIRCLE_TAG .
      - run:
          name: Build Docker image
          command: |              
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin          
            docker push $IMAGE_NAME:$CIRCLE_TAG
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master    
            tags:
              only: /^v.*/  