version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/buildpack-deps:stretch # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: env

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master                
            tags:
              only: /^v.*/          