version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: emrahkk/kube-echo
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |                        
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            tag=$(git tag --points-at HEAD|grep "^v.*")            
            if [ -z "$tag" ]
            then
                  docker build -t emrahkk/kube-echo:latest .                  
            else
                  docker build -t emrahkk/kube-echo:latest -t emrahkk/kube-echo:$tag .
                  docker push emrahkk/kube-echo:$tag
            fi                     
            docker push emrahkk/kube-echo:latest       
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master      