version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: emrahkk/kube-echo
      TAG: << pipeline.git.tag >>
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |                        
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$TAG .
            docker push $IMAGE_NAME            
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master    
            tags:
              only: /^v.*/  