version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/buildpack-deps:stretch # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world 1" # run the `echo` command      
  release:
    docker: 
      - image: circleci/buildpack-deps:stretch # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world 2" # run the `echo` command    
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - release:
          filters:                
              tags:
                only: /^v.*/          