version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: emrahkk/kube-echo
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            git version
            echo 'export TAG=$(git tag --points-at HEAD|grep "^v.*")' >> $BASH_ENV
            source $BASH_ENV            
            echo $TAG
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master      