version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: emrahkk/kube-echo
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |            
            tag=$(git tag --points-at HEAD|grep "^v.*")
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            if [ -z "$tag" ]
            then
                  docker build -t $IMAGE_NAME:latest .                  
            else
                  docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$tag .
                  docker push $IMAGE_NAME:$tag
            fi                     
            docker push $IMAGE_NAME:latest        
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master      