version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/buildpack-deps:stretch # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory      
      - run:
          name: Build docker
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin            
  deploy:
    docker: 
      - image: circleci/buildpack-deps:stretch # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory      
      - run:
          name: Build docker image 
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker build -t emrahkk/kube-echo:latest .
            docker push emrahkk/kube-echo:latest

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/