apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESAPCE}
spec:
  type: LoadBalancer
  loadBalancerIP: ${SERVICE_IP}
  ports:
  - port: 80
    targetPort: ${APP_PORT}
  selector:
    app: ${APP_NAME}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESAPCE}
  labels:
    app: ${APP_NAME}
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
      - name: ${APP_NAME}
        image: ${APP_IMAGE}
        ports:
        - containerPort: ${APP_PORT}
        livenessProbe:
          httpGet:
            path: /healthz
            port: ${APP_PORT}                        
          initialDelaySeconds: 15
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /readyz
            port: ${APP_PORT}
          failureThreshold: 30
          periodSeconds: 10
        env:
        - name: ENVR
          value: ${ENV}
      imagePullSecrets:
        - name: ibb-gitlab-registry