apiVersion: v1
kind: Service
metadata:
  name: ${APP_DEPLOY_NAME}
  namespace: ibb
spec:
  type: LoadBalancer
  loadBalancerIP: 10.5.26.66
  ports:
  - port: 80
    targetPort: ${APP_PORT}
  selector:
    app: ${APP_DEPLOY_NAME}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ${APP_DEPLOY_NAME}
  namespace: ibb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ${APP_DEPLOY_NAME}
    spec:
      containers:
      - name: ${APP_DEPLOY_NAME}
        image: ${APP_IMAGE_TAG}                  
        ports:
        - containerPort: ${APP_PORT}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000                        
          initialDelaySeconds: 15
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /readyz
            port: 3000
          failureThreshold: 30
          periodSeconds: 10
      nodeSelector:
        host-lbl: worker2
      imagePullSecrets:
        - name: ibb-gitlab-registry
