# Example configuration for the webserver
# at https://github.com/monopole/hello
commonLabels:
  app: hello

namePrefix: dev-

replicas:
- name: the-deployment
  count: 5

resources:
- deployment.yaml
- service.yaml
- configMap.yaml
